## Numpy Array Operations

In [1]:
import numpy as np

## Basic Slicing

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print("Basic Slicing: ", arr[3 : 8])
print("With Step: ", arr[1 : 11 : 2])
print("Negative index Slicing: ", arr[-1 : 0 : -2])

Basic Slicing:  [4 5 6 7 8]
With Step:  [ 2  4  6  8 10]
Negative index Slicing:  [10  8  6  4  2]


## Slicing on Multi-dimensional Array

In [ ]:
arr_2d = np.arange(1, 17).reshape(4,4)
print("Original Array: \n", arr_2d)

# getting element at 2nd row and 3rd column
print("\nParticular Element: ", arr_2d[1, 2])

print("\nEntire Row: ", arr_2d[2])# print row 3
print("\nEntire Column: ", arr_2d[:, 2]) # pirnt column 3

print("\nAdvance Slicing: ", arr_2d[ 3,-1::-1]) # this print the last row in reverse order

Original Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Particular Element:  7

Entire Row:  [ 9 10 11 12]

Entire Column:  [ 3  7 11 15]

Advance Slicing:  [16 15 14 13]


## Sorting