## Creation of Arrays by NUMPY

In [37]:
import numpy as np

In [38]:
# we can also specify the data type during the intialization of array.
arr_1d = np.array([1,2,3], dtype = np.float16) 
print("Vector : ",arr_1d)

arr_2d = np.array([[1,2,3],
                   [4,5,6]], dtype = np.int32)
print("Matrices : \n\n",arr_2d)

arr_3d = np.array([[[1,2], [4,5]],
                   [[6,7], [8,9]],
                   [[10,11], [12,13]]])
print("Tensor : \n\n", arr_3d)

Vector :  [1. 2. 3.]
Matrices : 

 [[1 2 3]
 [4 5 6]]
Tensor : 

 [[[ 1  2]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


# Properties of Arrays

In [39]:
#Size means the total number of elements in the array
size2 = arr_2d.size
size3 = arr_3d.size

print("Size of Matrix: ", size2)
print("Size of Tensor: ", size3)

dim2 = arr_2d.ndim
dim3 = arr_3d.ndim

print("Dimension of Matrix: ", dim2)
print("Dimension of Tensor: ", dim3)


shape2 = arr_2d.shape
shape3 = arr_3d.shape

print("Shape of Matrix: ", shape2)
print("Shape of Tensor: ", shape3)

dtype2 = arr_2d.dtype
dtype3 = arr_3d.dtype

#showing int32 because we specified it during initialization
print("Data Type of Matrix: ", dtype2)
print("Date Type of Tensor: ", dtype3)

#Item size means the actual size in byte that a particular piece 
# of date is taking from memory to store it.
itemsize2 = arr_2d.itemsize
itemsize3 = arr_3d.itemsize

print("Item Size of Matrix: ", itemsize2) #int32 takes 4 bytes
print("Item Size of Tensor: ", itemsize3) #int64 takes 8 bytes

Size of Matrix:  6
Size of Tensor:  12
Dimension of Matrix:  2
Dimension of Tensor:  3
Shape of Matrix:  (2, 3)
Shape of Tensor:  (3, 2, 2)
Data Type of Matrix:  int32
Date Type of Tensor:  int64
Item Size of Matrix:  4
Item Size of Tensor:  8


## Creating Basic Arrays

In [40]:
#Zeros is the type of array in which all the elements are 0.
zero_matrice = np.zeros((2,3))
print("Zero Matrice: \n", zero_matrice)

#Ones is the type of array in which all the elements are 1.
ones_matrice = np.ones((2,2), dtype = np.int8)
print("Ones Matrice: \n", ones_matrice)

#Empty is the type of array in which all the elements are empty
empty_matrice = np.empty((3,2), dtype = np.int64)
print("Empty Matrice: \n", empty_matrice)

#Full is the type of array in which all the are same value is provided.
full_matrice = np.full((3,3), 7)
print("Full Matice: \n", full_matrice)

Zero Matrice: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Matrice: 
 [[1 1]
 [1 1]]
Empty Matrice: 
 [[0 0]
 [0 0]
 [0 0]]
Full Matice: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


## Arange & Reshape Functions

In [41]:
#Arange function to create the array (vector or 1d) in a range of numbers. 
#It works just like range function of python
#SYNTAX: arange(start, stop, step, dtype)

arr_1d = np.arange(3, 31, 3) #prints tabel of 3
print("Tabel of 3 Using arange: \n", arr_1d)
print("Dimension of Tabel: ", arr_1d.ndim)

#We can use the reshape function to change the shape of the array and
# It also change the dimension.

arr_2d = arr_1d.reshape(5, 2)
print("Reshaped Array: \n", arr_2d)
print("Dimension of Reshaped Array: ", arr_2d.ndim)

arr_4d = np.arange(1, 17).reshape(2,2,2,2)
print("4D Array Reshaped from 1d: \n", arr_4d)
print("Dimension of 4D Array: ", arr_4d.ndim)


Tabel of 3 Using arange: 
 [ 3  6  9 12 15 18 21 24 27 30]
Dimension of Tabel:  1
Reshaped Array: 
 [[ 3  6]
 [ 9 12]
 [15 18]
 [21 24]
 [27 30]]
Dimension of Reshaped Array:  2
4D Array Reshaped from 1d: 
 [[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Dimension of 4D Array:  4


## Flatten & Ravel

In [42]:
# We have flatten function which used to convert
# multi-dimensional array to a 1d array.

arr_4d_flattened = arr_4d.flatten()
print("Flattened Array: \n", arr_4d_flattened)
print("Dimension of Flattened Array: ", arr_4d_flattened.ndim)

# We Use another function to flatten the array which is ravel but
# the differnce is flatten(): Always returns a new independent copy 
# of the array. Modifications to the flattened array will not affect 
# the original array.
# ravel(): Returns a contiguous flattened array.This means if the memory 
# layout allows, ravel() will return a reference to the original data.

print("Ravaled Array: \n", arr_4d.ravel())
print("Dimension of Ravaled Array: ", arr_4d.ndim)

Flattened Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Dimension of Flattened Array:  1
Ravaled Array: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Dimension of Ravaled Array:  4


# Linespace Funtion

In [ ]:
# We can use floating point numbers as arguments in the arange function.
# But the problem is that if we give the step as a floating point we have limit of precision for that we use a differnt function named : 
# linespace(start, stop, count_of_numbers_want_between_start_stop)
# linspace is the function to create the array in a range of numbers.
floating_arr = np.linspace(0, 1, 6)
print("Array of 6 floating point numbers from 0 to 1: \n", floating_arr)

Array of 6 floating point numbers from 0 to 1: 
 [0.  0.2 0.4 0.6 0.8 1. ]


## Transpose (row -> column)

In [54]:
# We can use the transpose function to transpose an array it means
# it interchange the columns with rows.

og_array = np.arange(1, 7).reshape(2,3) 
print("Original Array: \n", og_array)
print("Shape of Original Array: ", og_array.shape)
print("Dimension of Original Array: ", og_array.ndim)

transpose_arr = og_array.T
print("Transposed Array: \n", transpose_arr)
print("Shape of Transposed Array: ", transpose_arr.shape)
print("Dimension of Transposed Array: ", transpose_arr.ndim)
 

Original Array: 
 [[1 2 3]
 [4 5 6]]
Shape of Original Array:  (2, 3)
Dimension of Original Array:  2
Transposed Array: 
 [[1 4]
 [2 5]
 [3 6]]
Shape of Transposed Array:  (3, 2)
Dimension of Transposed Array:  2
